[package]
name = "mdbook-yapp"
version = "0.0.0"
authors = ["Dariusz Depta <wisbery@users.noreply.github.com>"]
description = "A mdbook preprocessor for simple replacement patterns"
documentation = "https://docs.rs/mdbook-yapp"
repository = "https://github.com/wisbery/yapp.git"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
