[package]
name = "mdbook-yapp"
version = "0.0.1"
authors = ["Dariusz Depta <wisbery@users.noreply.github.com>"]
description = "A mdbook preprocessor for simple replacement patterns"
documentation = "https://docs.rs/mdbook-yapp"
repository = "https://github.com/wisbery/yapp.git"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
clap = "4.4.7"
mdbook = "0.4.35"
semver = "1.0.20"
serde_json = "1.0.108"