[package]
name = "mdbook-yapp"
version = "0.0.3"
authors = ["Dariusz Depta <wisbery@users.noreply.github.com>"]
description = "A mdbook preprocessor for simple text replacements"
documentation = "https://docs.rs/mdbook-yapp"
repository = "https://github.com/wisbery/yapp.git"
keywords = ["mdbook", "preprocessor", "replace", "text", "pattern"]
categories = ["template-engine", "text-processing"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
clap = "4.5.3"
mdbook = "0.4.37"
semver = "1.0.22"
serde_json = "1.0.114"
